from __future__ import annotations

from .registry import BundleConfig


def render_safebox_env(bundle: BundleConfig) -> str:
    safebox_web = bundle.require_service("safebox_web")
    clear = bundle.require_service("clear")
    grove = bundle.require_service("grove")
    spurline = bundle.require_service("spurline")

    values = {
        "SAFEBOX_COOKIE_KEY": bundle.secrets.get("safebox_cookie_key", ""),
        "CLEAR_MASTER_SECRET": bundle.secrets.get("clear_master_secret", ""),
        "CLEAR_OPERATOR_TOKEN": bundle.secrets.get("clear_operator_token", ""),
        "SAFEBOX_BIND_ADDRESS": safebox_web.bind_address or "127.0.0.1",
        "SAFEBOX_PORT": str(safebox_web.port or 8000),
        "FORWARDED_ALLOW_IPS": bundle.forwarded_allow_ips,
        "SAFEBOX_DEFAULT_BOOTSTRAP_RELAY": spurline.local_url,
        "SAFEBOX_ALLOWED_WS_RELAYS": spurline.local_url,
        "SAFEBOX_SERVICE_ACORN_HOME_RELAY": spurline.local_url,
        "SPURLINE_PUBLIC_URL": spurline.advertised_url,
        "SAFEBOX_DEFAULT_HOME_MINT": clear.local_url,
        "SAFEBOX_SERVICE_ACORN_HOME_MINT": clear.local_url,
        "SAFEBOX_CLEAR_RECEIVE_ENABLED": "true" if clear.enabled else "false",
        "SAFEBOX_CLEAR_MINTS": clear.local_url if clear.enabled else "",
        "CLEAR_MINT_URL": clear.advertised_url,
        "SAFEBOX_BLOSSOM_HOME_SERVER": grove.local_url,
        "GROVE_PUBLIC_URL": grove.advertised_url,
        "SAFEBOX_CURRENCY_RATES_ENABLED": "false",
        "CLEAR_CURRENCY_NAME": bundle.clear_currency_name,
    }

    lines = [
        "# Generated by mainstay-local. Fill blank secrets before starting.",
    ]
    lines.extend(f"{key}={_quote_env(value)}" for key, value in values.items())
    lines.append("")
    return "\n".join(lines)


def _quote_env(value: str) -> str:
    if value == "":
        return ""
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'
