from __future__ import annotations

from .registry import BundleConfig


def render_safebox_env(bundle: BundleConfig) -> str:
    safebox_web = bundle.require_service("safebox_web")
    clear = bundle.require_service("clear")
    grove = bundle.require_service("grove")
    spurline = bundle.require_service("spurline")
    clear_internal = clear.require_url("internal", purpose="mint")
    clear_mints = ",".join(
        mint
        for mint in (clear_internal, bundle.external_clear_mint_url)
        if mint
    )
    grove_internal = grove.require_url("internal", purpose="blossom")
    spurline_internal = spurline.require_url("internal", purpose="relay")

    values = {
        "SAFEBOX_COOKIE_KEY": bundle.secrets.get("safebox_cookie_key", ""),
        "SAFEBOX_ONBOARD_INVITE_CODE": bundle.secrets.get(
            "safebox_onboard_invite_code", ""
        ),
        "SAFEBOX_WEB_SERVICE_NSEC": bundle.secrets.get(
            "safebox_web_service_nsec", ""
        ),
        "SAFEBOX_WEB_SERVICE_MANAGEMENT": "mainstay-managed",
        "SAFEBOX_ALLOW_INSECURE_HTTP": "true",
        "CLEAR_MASTER_SECRET": bundle.secrets.get("clear_master_secret", ""),
        "CLEAR_OPERATOR_TOKEN": bundle.secrets.get("clear_operator_token", ""),
        "CLEAR_MINT_SERVICE_NSEC": bundle.secrets.get(
            "clear_mint_service_nsec", ""
        ),
        "CLEAR_MINT_SERVICE_MANAGEMENT": "mainstay-managed",
        "GROVE_SERVICE_NSEC": bundle.secrets.get("grove_service_nsec", ""),
        "GROVE_SERVICE_MANAGEMENT": "mainstay-managed",
        "SPURLINE_SERVICE_NSEC": bundle.secrets.get(
            "spurline_service_nsec", ""
        ),
        "SPURLINE_SERVICE_MANAGEMENT": "mainstay-managed",
        "MAINSTAY_SAFEBOX_BIND_ADDRESS": safebox_web.bind_address or "0.0.0.0",
        "MAINSTAY_SAFEBOX_PORT": str(safebox_web.port or 8888),
        "FORWARDED_ALLOW_IPS": bundle.forwarded_allow_ips,
        "SAFEBOX_DEFAULT_BOOTSTRAP_RELAY": spurline_internal,
        "SAFEBOX_ALLOWED_WS_RELAYS": spurline_internal,
        "SAFEBOX_SERVICE_ACORN_HOME_RELAY": spurline_internal,
        "SAFEBOX_SERVICE_ACORN_ENABLED": "true",
        "SPURLINE_PUBLIC_URL": spurline.preferred_url(purpose="relay"),
        "MAINSTAY_LIGHTNING_MINT_URL": bundle.lightning_mint_url,
        "SAFEBOX_DEFAULT_HOME_MINT": bundle.lightning_mint_url,
        "SAFEBOX_SERVICE_ACORN_HOME_MINT": bundle.lightning_mint_url,
        "SAFEBOX_CLEAR_RECEIVE_ENABLED": "true" if clear.enabled else "false",
        "MAINSTAY_EXTERNAL_CLEAR_MINT_URL": bundle.external_clear_mint_url,
        "SAFEBOX_CLEAR_MINTS": clear_mints if clear.enabled else "",
        "SAFEBOX_CLEAR_EXTERNAL_MINTS": (
            bundle.external_clear_mint_url if clear.enabled else ""
        ),
        "CLEAR_MINT_URL": clear.preferred_url(purpose="mint"),
        "SAFEBOX_BLOSSOM_HOME_SERVER": grove_internal,
        "SAFEBOX_MAINSTAY_CONTEXT_URL": "http://mainstay-local:8788/context",
        "GROVE_PUBLIC_URL": grove.preferred_url(purpose="blossom"),
        "SAFEBOX_CURRENCY_RATES_ENABLED": "true",
        "SAFEBOX_CURRENCY_RATE_SOURCE_URL": "https://blockchain.info/ticker",
        "SAFEBOX_CURRENCY_RATE_INTERVAL_SECONDS": "3600",
        "SAFEBOX_CURRENCY_RATE_CURRENCIES": (
            "CAD,USD,EUR,GBP,JPY,INR,CNY,AUD,CHF,SGD,HKD,BRL"
        ),
        "SAFEBOX_DEFAULT_DISPLAY_CURRENCY": "USD",
        "SAFEBOX_CURRENCY_RATE_STALE_SECONDS": "86400",
        "CLEAR_CURRENCY_NAME": bundle.clear_currency_name,
    }

    lines = [
        "# Generated by mainstay-local. Fill blank secrets before starting.",
    ]
    lines.extend(f"{key}={_quote_env(value)}" for key, value in values.items())
    lines.append("")
    return "\n".join(lines)


def _quote_env(value: str) -> str:
    if value == "":
        return ""
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'
