from __future__ import annotations

from .registry import BundleConfig


def render_safebox_env(bundle: BundleConfig) -> str:
    safebox_web = bundle.require_service("safebox_web")
    clear = bundle.require_service("clear")
    grove = bundle.require_service("grove")
    spurline = bundle.require_service("spurline")
    clear_internal = clear.require_url("internal", purpose="mint")
    grove_internal = grove.require_url("internal", purpose="blossom")
    spurline_internal = spurline.require_url("internal", purpose="relay")

    values = {
        "SAFEBOX_COOKIE_KEY": bundle.secrets.get("safebox_cookie_key", ""),
        "SAFEBOX_ONBOARD_INVITE_CODE": bundle.secrets.get(
            "safebox_onboard_invite_code", ""
        ),
        "SAFEBOX_ALLOW_INSECURE_HTTP": "true",
        "SAFEBOX_ALLOW_INSECURE_MINTS": "true",
        "CLEAR_MASTER_SECRET": bundle.secrets.get("clear_master_secret", ""),
        "CLEAR_OPERATOR_TOKEN": bundle.secrets.get("clear_operator_token", ""),
        "MAINSTAY_SAFEBOX_BIND_ADDRESS": safebox_web.bind_address or "0.0.0.0",
        "MAINSTAY_SAFEBOX_PORT": str(safebox_web.port or 8888),
        "FORWARDED_ALLOW_IPS": bundle.forwarded_allow_ips,
        "SAFEBOX_DEFAULT_BOOTSTRAP_RELAY": spurline_internal,
        "SAFEBOX_ALLOWED_WS_RELAYS": spurline_internal,
        "SAFEBOX_SERVICE_ACORN_HOME_RELAY": spurline_internal,
        "SPURLINE_PUBLIC_URL": spurline.preferred_url(purpose="relay"),
        "SAFEBOX_DEFAULT_HOME_MINT": clear_internal,
        "SAFEBOX_SERVICE_ACORN_HOME_MINT": clear_internal,
        "SAFEBOX_CLEAR_RECEIVE_ENABLED": "true" if clear.enabled else "false",
        "SAFEBOX_CLEAR_MINTS": clear_internal if clear.enabled else "",
        "CLEAR_MINT_URL": clear.preferred_url(purpose="mint"),
        "SAFEBOX_BLOSSOM_HOME_SERVER": grove_internal,
        "GROVE_PUBLIC_URL": grove.preferred_url(purpose="blossom"),
        "SAFEBOX_CURRENCY_RATES_ENABLED": "false",
        "CLEAR_CURRENCY_NAME": bundle.clear_currency_name,
    }

    lines = [
        "# Generated by mainstay-local. Fill blank secrets before starting.",
    ]
    lines.extend(f"{key}={_quote_env(value)}" for key, value in values.items())
    lines.append("")
    return "\n".join(lines)


def _quote_env(value: str) -> str:
    if value == "":
        return ""
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'
